apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-deployment
  labels:
    app: messenger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: cr.selcloud.ru/lazyweb/messenger
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: messenger-config
        - name: postgres
          image: postgres
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: messenger-config