apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-deployment
  labels:
    app: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: lazyboo/messenger:v1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: messenger-config